version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
    day: 'monday'
    time: '10:00'
    timezone: 'Asia/Tokyo'
  open-pull-requests-limit: 5
  reviewers:
    - yasudanaoya
  labels:
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  ignore:
    - dependency-name: sass-loader
      versions: [11.x, 12.x]

# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    day: 'monday'
    time: '10:00'
    timezone: 'Asia/Tokyo'

  open-pull-requests-limit: 5
  reviewers:
    - yasudanaoya
  labels:
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
